spring.application.name=ProjectPBO
# Koneksi ke MySQL/MariaDB (HeidiSQL)
spring.datasource.url=jdbc:mysql://localhost:3306/db_trash?createDatabaseIfNotExist=true
spring.datasource.username=root
spring.datasource.password=root

# Hibernate setup
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

spring.servlet.multipart.max-file-size=50MB
spring.servlet.multipart.max-request-size=50MB
spring.devtools.restart.exclude=static/img/uploads/**,target/**

# Karena kita pakai Lombok, pastikan annotation processing nyala di IDE